name: ai
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - requests
  - xarray
  - netcdf4
  - h5py
  - matplotlib
  - plotly
  - seaborn
  - cartopy
  - geos
  - proj
  - pyproj
  - shapely
  - pyshp
  - dask
  - openpyxl
  - boto3
  - pip:
      - any-llm-sdk==0.6.0